version: 4.6.{build}

environment:
  twitApi:
    secure: ukcYar2X3Solh3Xaj/x6TV4ZxpaXWWxKWBSB1fxpBp8=
  twiApiSecure:
    secure: dzs3u7ctD2UFRTaaOLuR8Mnrdkb+o9AcCxSDThbMMmbcg854TJ+0cqvujFtcnbjLSCz/Sb0u5RPFjb2nhejGbw==
  accessToken:
    secure: E9fYMRsZvLC/R22S8YPRdFA9okfxfAf7vzeAB4F5kyCqgk6Ek1itDqkIWIYb34Rw3y/1Ak3ofSJkdKXna51ALw==
  accessTokenSecret:
    secure: xbVDi+rwp6jQ3YQCMTxNriOuFaWG0eK0EOakbtSwdenfOGMxdhDHu4IKnlXgohXc
  NuGetApiKey:
    secure: OX4AxdrgR7cWD+b3x/ZcjN87ij7UM1+HYsd/L3CJKxAkJ2ZEX3lIgvWDuoTMcKNM

skip_tags: true

install:
  - git submodule -q update --init
  - git clone https://github.com/PowerShell/DscResource.Tests

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  - ps: |
        Write-Host "Setting version number in files"
        Add-AppveyorMessage -Message "Setting version number in files" -Category Information
        gci -Filter *.psd1 -Recurse | foreach {(Get-Content $_.FullName -Raw) -replace "ModuleVersion = '\d\.\d\.\d\.\d'", "ModuleVersion = '$env:APPVEYOR_BUILD_VERSION'" | Out-File $_.FullName}
        Write-Host "Calling build script"
        .\Build.ps1

build:
  project: AutomatedLab.sln

after_build:
  - ps: |
        Write-Host "Locating installer to push as artifact"
        Add-AppveyorMessage "Locating installer to push as artifact" -Category Information
        $msifile = Get-ChildItem -Recurse -Filter AutomatedLab.msi | Select-Object -First 1
        Push-AppVeyorArtifact $msifile.FullName -FileName $msifile.Name -DeploymentName alinstaller

deploy:
  release: AutomatedLab-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: DpSClhfGRzvQY114F1GU9MwQAtey6LVSKc8DkIsQhMEkCSiBN0a/mytsr3y/nsIu # your encrypted token from GitHub
  artifact: alinstaller            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only

after_deploy:
  ps: |
        Write-Host "Downloading Twitter module"
        iex (New-Object Net.WebClient).DownloadString("https://gist.githubusercontent.com/stefanstranger/2138dc710576bc40b64b/raw/bfd25a0e7363e9a1906908b0695ebcffaa508276/InstallMyTwitterModule.ps1")

        if (Get-Module MyTwitter -List)
        {
          New-MyTwitterConfiguration -APIKey $env:twitApi -APISecret $env:twiApiSecure -AccessToken $env:accessToken -AccessTokenSecret $env:accessTokenSecret -Force -Verbose:$false
          $tweets = @(
              "#AutomatedLab just released v{0}! See our changelog at: {1} Get it while it's hot! #PowerShell #Automation"
              "It's time for a new release :) #AutomatedLab v{0} is out now! Check out what has changed: {1} #PowerShell #Automation"
              "#AutomatedLab v{0} is now live! Check out our changelog at {1}! #PowerShell #Automation"
              "What? AutomatedLab has released v{0}? Awesome :) Check out our changelog at {1}! #PowerShell #Automation"
          )
          $rnd = Get-Random -Minimum 0 -Maximum ($tweets.Length -1)
          [void] (Send-Tweet -Message ($tweets[$rnd] -f $env:APPVEYOR_BUILD_VERSION, 'https://github.com/AutomatedLab/AutomatedLab/blob/develop/CHANGELOG.md'))
        }
