version: 4.6.{build}

skip_tags: true

install:
  - git submodule -q update --init
  - git clone https://github.com/PowerShell/DscResource.Tests

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
  -ps: |
        Write-Host "Setting version number in files"
        Add-AppveyorMessage -Message "Setting version number in files" -Category Information
        gci -Filter *.psd1 -Recurse | foreach {(Get-Content $_.FullName -Raw) -replace "ModuleVersion = '\d\.\d\.\d\.\d'", "ModuleVersion = '$env:APPVEYOR_BUILD_VERSION'" | Out-File $_.FullName}

build:
  project: AutomatedLab.sln

after_build:
  - ps: |
        # Find MSIs
        Write-Host "Locating installer to push as artifact"
        Add-AppveyorMessage "Locating installer to push as artifact" -Category Information
        $msifile = Get-ChildItem -Recurse -Filter AutomatedLab.msi | Select-Object -First 1
        Push-AppVeyorArtifact $msifile.FullName -FileName $msifile.Name -DeploymentName alinstaller

deploy:
  release: AutomatedLab-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: DpSClhfGRzvQY114F1GU9MwQAtey6LVSKc8DkIsQhMEkCSiBN0a/mytsr3y/nsIu # your encrypted token from GitHub
  artifact: alinstaller            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only